export const DEVICE_STATUS = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
};

export const GATE_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  OPENING: 'OPENING',
  CLOSING: 'CLOSING',
  UNKNOWN: 'UNKNOWN',
};

export const DEVICE_MODE = {
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
};

export const COMMAND_TYPES = {
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  SET_SCHEDULE: 'SET_SCHEDULE',
  SET_MODE: 'SET_MODE',
};

export const COMMAND_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  FAILED: 'FAILED',
};

export const EVENT_TYPES = {
  DEVICE_ONLINE: 'DEVICE_ONLINE',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  GATE_OPENED: 'GATE_OPENED',
  GATE_CLOSED: 'GATE_CLOSED',
  GATE_OPENING: 'GATE_OPENING',
  GATE_CLOSING: 'GATE_CLOSING',
  COMMAND_SENT: 'COMMAND_SENT',
  COMMAND_ACKNOWLEDGED: 'COMMAND_ACKNOWLEDGED',
  SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
  MODE_CHANGED: 'MODE_CHANGED',
  HEARTBEAT: 'HEARTBEAT',
  ERROR: 'ERROR',
};

export const DAYS_OF_WEEK = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];
