export const DEVICE_TYPES = {
  GATE: 'GATE',
  STREET_LIGHT: 'STREET_LIGHT',
};

export const DEVICE_STATUS = {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
};

export const GATE_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  OPENING: 'OPENING',
  CLOSING: 'CLOSING',
  UNKNOWN: 'UNKNOWN',
};

export const LIGHT_STATUS = {
  ON: 'ON',
  OFF: 'OFF',
  DIM: 'DIM',
  ADAPTIVE: 'ADAPTIVE',
};

export const DEVICE_MODE = {
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
};

export const COMMAND_TYPES = {
  // Gate Commands
  OPEN: 'OPEN',
  CLOSE: 'CLOSE',
  SET_SCHEDULE: 'SET_SCHEDULE',
  SET_MODE: 'SET_MODE',

  // Street Light Commands
  TURN_ON: 'TURN_ON',
  TURN_OFF: 'TURN_OFF',
  SET_LIGHT_MODE: 'SET_LIGHT_MODE',
  SET_BRIGHTNESS: 'SET_BRIGHTNESS',
  SET_ZONE: 'SET_ZONE',
};

export const COMMAND_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  FAILED: 'FAILED',
};

export const EVENT_TYPES = {
  DEVICE_ONLINE: 'DEVICE_ONLINE',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  GATE_OPENED: 'GATE_OPENED',
  GATE_CLOSED: 'GATE_CLOSED',
  GATE_OPENING: 'GATE_OPENING',
  GATE_CLOSING: 'GATE_CLOSING',
  LIGHT_TURNED_ON: 'LIGHT_TURNED_ON',
  LIGHT_TURNED_OFF: 'LIGHT_TURNED_OFF',
  MOTION_DETECTED: 'MOTION_DETECTED',
  AMBIENT_CHANGED: 'AMBIENT_CHANGED',
  COMMAND_SENT: 'COMMAND_SENT',
  COMMAND_ACKNOWLEDGED: 'COMMAND_ACKNOWLEDGED',
  SCHEDULE_UPDATED: 'SCHEDULE_UPDATED',
  MODE_CHANGED: 'MODE_CHANGED',
  HEARTBEAT: 'HEARTBEAT',
  TELEMETRY: 'TELEMETRY',
  ERROR: 'ERROR',
};

export const DAYS_OF_WEEK = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];
